// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzqfnuttghsivscjsfap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6cWZudXR0Z2hzaXZzY2pzZmFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyODY0NzgsImV4cCI6MjA2ODg2MjQ3OH0.Kjhat4Dgi6zeurmW8U8pybMlbdtn1PMimN8KbIVHfcI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});